spring.application.name=taskmanager

server.port = 8080

#Database URL
spring.datasource.url = jdbc:mysql://localhost:3306/taskManagersql

#include the link and port number which is equal to the list opf the DPF

#Username and password
spring.datasource.username = root
spring.datasource.password = Aman@202220

#MySQL Driver
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

#JPA/Hibernate Settings

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Dialect
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect



